# Generated by Django 3.1.6 on 2021-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('district', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=250)),
                ('occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Farmer', 'Farmer'), ('House Wife', 'House Wife'), ('Technician', 'Technician'), ('Student', 'Student')], max_length=100)),
            ],
        ),
    ]
