# Generated by Django 3.1.6 on 2021-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnosis', models.CharField(choices=[('A00-B99', ' Certain infectious and parasitic diseases'), ('C00-D49', 'Neoplasms'), ('D50-D89', 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism'), ('E00-E89', 'Endocrine, nutritional and metabolic diseases'), ('F01-F99', 'Mental, Behavioral and Neurodevelopmental disorders'), ('G00-G99', 'Diseases of the nervous system'), ('H00-H59', 'Diseases of the eye and adnexa'), ('H60-H95', 'Diseases of the ear and mastoid process'), ('I00-I99', 'Diseases of the circulatory system'), ('J00-J99', 'Diseases of the respiratory system'), ('K00-K95', 'Diseases of the digestive system'), ('L00-L99', 'Diseases of the skin and subcutaneous tissue'), ('M00-M99', 'Diseases of the musculoskeletal system and connective tissue'), ('N00-N99', 'Diseases of the genitourinary system'), ('O00-O9A', 'Pregnancy, childbirth and the puerperium'), ('P00-P96', 'Certain conditions originating in the perinatal period'), ('Q00-Q99', 'Congenital malformations, deformations and chromosomal abnormalities'), ('R00-R99', 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified'), ('S00-T88', 'Injury, poisoning and certain other consequences of external causes'), ('U00-U85', 'Codes for special purposes'), ('V00-Y99', 'External causes of morbidity'), ('Z00-Z99', 'Factors influencing health status and contact with health services')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('district', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=250)),
                ('occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Farmer', 'Farmer'), ('House Wife', 'House Wife'), ('Technician', 'Technician'), ('Student', 'Student')], max_length=100)),
            ],
        ),
    ]
