# Generated by Django 3.1.6 on 2021-02-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_assessment_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-visit_date']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name']},
        ),
    ]
